name: PR Check Links

permissions: {}

on:
  pull_request_target:
    # edited is needed here as this workflow checks for PR meta content
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  check-pr-links:
    uses: peppi-lotta/workflow-test/.github/workflows/PR-bronken-link-check.yaml@master